package BatailleNavale;

import ProjetJava.Membre;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.io.IOException;
import java.util.Observable;
import java.util.Observer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Utilisateur
 */
public class JframeTest extends javax.swing.JFrame implements Observer {
    private PanelGrilleBN grille;
    private Membre mem;
    /**
     * Creates new form JframeTest
     * me permet de tester mes panels, ignore cette classe.
     */
    public JframeTest() throws Exception {
        initComponents();
        mem=new Membre("Aah","B0otah",false);
        /*GrilleBN g = new GrilleBN();
        grille = new PanelGrilleBNIA(g);
        add(grille, BorderLayout.CENTER);
        grille.redimensionner(380);*/
        BatailleNavale b = new BatailleNavale(mem,0);
        add(b.getPanel(), BorderLayout.CENTER);
        System.out.println(BatailleNavale.description());
        
        this.setVisible(true);
        b.addObserver(this);
        b.jeu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1600, 800));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void update(Observable o, Object arg) {
        this.setVisible(false);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
