/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BatailleNavale;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.HashSet;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
/**
 *
 * @author aabdo
 */
public class PanelCaseBN extends javax.swing.JButton{
    private CaseBatailleNavale caseBN;
    private ImageIcon image;
    
    /**
     * crée un Panel à partir de la case c et charge l'image correspondante
     * @param c
     * @throws IOException si l'image n'est pas trouvée
     */
    public PanelCaseBN(CaseBatailleNavale c) throws IOException {
        initComponents();
        caseBN=c;
        image=new ImageIcon();
        chargeImage();
        setSize(16,16);
    }
    
    /**
     * charge l'image correspondante au type de la case
     * @throws IOException 
     */
    public void chargeImage() throws IOException{
        //System.out.println(caseBN.getCase().toString());
        //image = ImageIO.read(new File("BatailleNavaleIMG\\"+caseBN.getCase().toString()+".png"));
        image.setImage(ImageIO.read(new File("BatailleNavaleIMG\\"+caseBN.getCase().toString()+".png")));
        this.setIcon(image);
        //TODO: Charger les images des bateaux séparément.
    }
    
    /**
     * mets à jour l'image de la case
     * @throws IOException 
     */
    public void updateImage() throws IOException{
        int lo=this.getSize().height;
        image.setImage(ImageIO.read(new File("BatailleNavaleIMG\\"+caseBN.getCase().toString()+".png")));
        this.setIcon(image);
        redimensionner(lo);
        this.setVisible(true);
    }
    
    /**
     * mets à jour l'image de la case si un bateau est placé dessus
     * @param bateaux
     * @throws IOException 
     */
    public void updateImage(HashSet<Bateau> bateaux) throws IOException{
        int lo=this.getSize().height;
        String nomFic = "BatailleNavaleIMG\\";
        if(caseBN.getCase()!=TypeCase.bateau){
            nomFic+=caseBN.getCase().toString();
        }
        else{
            Bateau bat = null;
            int i=0;
            for(Bateau b:bateaux){
                switch(b.getSens()){
                    case horizontal:
                        if(b.getCaseInitiale().getY()==caseBN.getY() && b.getCaseInitiale().getX()<=caseBN.getX() && b.getCaseInitiale().getX()+b.getTaille()>caseBN.getX()){
                           bat=b;
                           i=caseBN.getX()-b.getCaseInitiale().getX();
                        }
                        break;
                    case vertical:
                        if(b.getCaseInitiale().getX()==caseBN.getX() && b.getCaseInitiale().getY()<=caseBN.getY() && b.getCaseInitiale().getY()+b.getTaille()>caseBN.getY()){
                           bat=b;
                           i=caseBN.getY()-b.getCaseInitiale().getY();
                        }
                        break;
                }
            }
            if(bat!=null){
                nomFic+=bat.getClass().getSimpleName()+"_"+bat.getSens()+"_"+i;
            }
        }
        nomFic+=".png";
        //System.out.println(nomFic);
        image.setImage(ImageIO.read(new File(nomFic)));
        this.setIcon(image);
        redimensionner(lo);
        this.setVisible(true);
    }
    
    /**
     * 
     * @return case logique correspondante
     */
    public CaseBatailleNavale getCase(){
        return caseBN;
    }
    
    /**
     * touche la case logique puis update l'image
     * @throws Exception 
     */
    public void touche() throws Exception{
        caseBN.touche();
        updateImage();
    }
    
    /**
     * 
     * @return 
     */
    @Override
    public String toString(){
        return("("+caseBN.getX()+","+caseBN.getY()+","+caseBN.getCase().toString()+")");
    }
    
    /**
     * redimensionne le panel pour avoir une longueur de l
     * @param l nouvelle longueur
     */
    public void redimensionner(int l){
        image.setImage(image.getImage().getScaledInstance(l, l, Image.SCALE_DEFAULT));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    // End of variables declaration                   

}
