/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BatailleNavale;

import java.awt.Image;
import javax.swing.ImageIcon;
/**
 *
 * @author aabdo
 */
public  abstract class PanelCaseBN extends javax.swing.JButton{
    protected CaseBN caseBN;
    protected ImageIcon image;
    
    /**
     * crée un Panel à partir de la case c et charge l'image correspondante
     * @param c
     */
    public PanelCaseBN(CaseBN c){
        initComponents();
        caseBN=c;
        image=new ImageIcon();
        setSize(16,16);
    }
    
    /**
     * mets à jour l'image de la case
     */
    abstract public void updateImage();
    
    /**
     * 
     * @return case logique correspondante
     */
    public CaseBN getCase(){
        return caseBN;
    }
    
    /**
     * touche la case logique puis update l'image
     * @throws BNException 
     */
    public void touche() throws BNException{
        caseBN.touche();
        updateImage();
    }
    
    /**
     * 
     * @return 
     */
    @Override
    public String toString(){
        return("("+caseBN.getX()+","+caseBN.getY()+","+caseBN.getCase().toString()+")");
    }
    
    /**
     * redimensionne le panel pour avoir une longueur de l
     * @param l nouvelle longueur
     */
    public void redimensionner(int l){
        //this.setSize(l, l);
        image.setImage(image.getImage().getScaledInstance(l, l, Image.SCALE_DEFAULT));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    // End of variables declaration                   

}
