/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjetJava;

/**
 *Panel pour changer le mot de passe du membre connecté.
 * @author edeux
 */
public class ChangerMdpPannel extends javax.swing.JPanel {

    
    /**
     * Creates new form ChangerMDPPannel
     */

    public ChangerMdpPannel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel4 = new javax.swing.JLabel();
        oldPassword = new javax.swing.JPasswordField();
        newPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        newPasswordValidation = new javax.swing.JPasswordField();
        validerButton = new javax.swing.JButton();
        retourButton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jLabel4.setText("Ancien mot de passe :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(48, 57, 0, 0);
        add(jLabel4, gridBagConstraints);

        oldPassword.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        oldPassword.setText("jPasswordField1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 105;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(46, 21, 0, 24);
        add(oldPassword, gridBagConstraints);

        newPassword.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        newPassword.setText("jPasswordField2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 105;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 21, 0, 24);
        add(newPassword, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jLabel3.setText("Nouveau mot de passe :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(43, 50, 0, 0);
        add(jLabel3, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jLabel5.setText("Confirmation du mot de passe :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(43, 24, 0, 0);
        add(jLabel5, gridBagConstraints);

        newPasswordValidation.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        newPasswordValidation.setText("jPasswordField3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 105;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 21, 0, 24);
        add(newPasswordValidation, gridBagConstraints);

        validerButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        validerButton.setText("Changer de mot de passe");
        validerButton.setMargin(new java.awt.Insets(3, 20, 3, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 86, 47, 0);
        add(validerButton, gridBagConstraints);

        retourButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        retourButton.setText("Retour");
        retourButton.setMargin(new java.awt.Insets(3, 20, 3, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        add(retourButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    public javax.swing.JButton getRetourButton(){
        return retourButton;
    }
    
    public javax.swing.JButton getValiderButton(){
        return validerButton;
    }
    
    public String getOldPassword(){
        String old = "";
        for (char c : oldPassword.getPassword()){
            old+=c;
        }
        return old;
    }
    
    public String getNewPassword(){
        String pwd = "";
        for (char c : newPassword.getPassword()){
            pwd+=c;
        }
        return pwd;
    }

    /**
     * Verrifie que les deux nouveaux mots de passes sont égaux.
     * @return Vrai si les deux mots de passe sont égaux.
     */
    public boolean isConfirmation(){
        String newP = "";
        for (char c:newPassword.getPassword()){
            newP+=c;
        }
        String newPC = "";
        for (char c:newPassword.getPassword()){
            newPC+=c;
        }
        return newP.equals(newPC);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField newPassword;
    private javax.swing.JPasswordField newPasswordValidation;
    private javax.swing.JPasswordField oldPassword;
    private javax.swing.JButton retourButton;
    private javax.swing.JButton validerButton;
    // End of variables declaration//GEN-END:variables
}
