/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjetJava;

/**
 * Panel pour choisir le jeu.
 * @author deux
 */
public class ChoixJeuPanel extends javax.swing.JPanel {

    /**
     * Cree le panel choix de jeu et ajoute une image pour chaque jeu.
     */
    public ChoixJeuPanel() {
        initComponents();
        
        
        //Tableau contenant tous les jeux.
        String jeux[] = {"pendu", "bataillenavale"};
        
        
        //Ajout d'une image pour chaque jeu.
        for (String jeu : jeux) {
            groupeJeuPanel.add(new ImageJeuPanel(jeu));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        groupeJeuPanel = new javax.swing.JPanel();
        retourButton = new javax.swing.JButton();

        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWeights = new double[] {0.2, 0.8};
        layout.rowWeights = new double[] {0.1, 0.7, 0.2};
        setLayout(layout);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Choix de jeu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(jLabel1, gridBagConstraints);

        groupeJeuPanel.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(groupeJeuPanel, gridBagConstraints);

        retourButton.setText("Retour");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        add(retourButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel groupeJeuPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton retourButton;
    // End of variables declaration//GEN-END:variables
}
