/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjetJava;

/**
 * Panel pour choisir le jeu.
 *
 * @author deux
 */
public class ChoixJeuPanel extends javax.swing.JPanel {

    /**
     * Cree le panel choix de jeu et ajoute une image pour chaque jeu.
     */
    public ChoixJeuPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        groupeJeuPanel = new javax.swing.JPanel();
        retourButton = new javax.swing.JButton();
        chgPwdButton = new javax.swing.JButton();
        statistiquesButton = new javax.swing.JButton();

        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWeights = new double[] {0.4, 0.6};
        layout.rowWeights = new double[] {0.1, 0.7, 0.2};
        setLayout(layout);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Choix de jeu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(jLabel1, gridBagConstraints);

        groupeJeuPanel.setFocusable(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(groupeJeuPanel, gridBagConstraints);

        retourButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        retourButton.setText("Deconnexion");
        retourButton.setMargin(new java.awt.Insets(3, 20, 3, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        add(retourButton, gridBagConstraints);

        chgPwdButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        chgPwdButton.setText("Changer de mot de passe");
        chgPwdButton.setMargin(new java.awt.Insets(3, 20, 3, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        add(chgPwdButton, gridBagConstraints);

        statistiquesButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        statistiquesButton.setText("Statistiques");
        statistiquesButton.setMargin(new java.awt.Insets(3, 20, 3, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        add(statistiquesButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    public javax.swing.JPanel getGroupeJeuPanel(){
        return groupeJeuPanel;
    }

    public javax.swing.JButton getRetourButton(){
        return retourButton;
    }
    
    public javax.swing.JButton getStatistiquesButton(){
        return statistiquesButton;
    }
    public javax.swing.JButton getChgPwdButton(){
        return chgPwdButton;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chgPwdButton;
    private javax.swing.JPanel groupeJeuPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton retourButton;
    private javax.swing.JButton statistiquesButton;
    // End of variables declaration//GEN-END:variables
}
