/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjetJava;

/**
 * Panel de l'image d'un jeu.
 *
 * @author deux
 */
public class ImageJeuPanel extends javax.swing.JPanel {

    private String nomJeu;

    /**
     * Creation du Panel et changement du titre et de l'image en fonction du
     * jeu.
     */
    public ImageJeuPanel(String nomJeu) {
        this.nomJeu = nomJeu;
        initComponents();
        titleLabel.setText(nomJeu);
        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjetJava/images/" + nomJeu + ".jpg")));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        imageLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(300, 315));
        setMinimumSize(new java.awt.Dimension(220, 240));
        setPreferredSize(new java.awt.Dimension(220, 240));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        java.awt.GridBagLayout layout1 = new java.awt.GridBagLayout();
        layout1.columnWidths = new int[] {200};
        layout1.rowHeights = new int[] {180, 30};
        setLayout(layout1);

        imageLabel.setBackground(new java.awt.Color(0, 0, 0));
        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imageLabel.setMaximumSize(new java.awt.Dimension(200, 180));
        imageLabel.setMinimumSize(new java.awt.Dimension(200, 180));
        imageLabel.setPreferredSize(new java.awt.Dimension(200, 180));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(imageLabel, gridBagConstraints);

        titleLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setLabelFor(imageLabel);
        titleLabel.setText("Titre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(titleLabel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        System.out.println(nomJeu);
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
