/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjetJava;

/**
 *
 * @author deux
 */
public class InscriptionPanel extends javax.swing.JPanel {

    /**
     * Creates new form InscriptionPanel
     */
    public InscriptionPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldPseudo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordFieldConfirmation = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jButtonInscription = new javax.swing.JButton();
        jButtonRetour = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Pseudo :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 10);
        jPanel1.add(jLabel1, gridBagConstraints);

        jTextFieldPseudo.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jTextFieldPseudo.setMaximumSize(new java.awt.Dimension(200, 25));
        jTextFieldPseudo.setMinimumSize(new java.awt.Dimension(100, 25));
        jTextFieldPseudo.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 10);
        jPanel1.add(jTextFieldPseudo, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Mot de passe :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 10);
        jPanel1.add(jLabel2, gridBagConstraints);

        jPasswordField.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jPasswordField.setMaximumSize(new java.awt.Dimension(200, 25));
        jPasswordField.setMinimumSize(new java.awt.Dimension(100, 25));
        jPasswordField.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 10);
        jPanel1.add(jPasswordField, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Mot de passe (confirmation):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 10);
        jPanel1.add(jLabel3, gridBagConstraints);

        jPasswordFieldConfirmation.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jPasswordFieldConfirmation.setMaximumSize(new java.awt.Dimension(200, 25));
        jPasswordFieldConfirmation.setMinimumSize(new java.awt.Dimension(100, 25));
        jPasswordFieldConfirmation.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 10);
        jPanel1.add(jPasswordFieldConfirmation, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(48, 25, 0, 0);
        add(jPanel1, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jButtonInscription.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jButtonInscription.setText("Inscription");
        jButtonInscription.setMargin(new java.awt.Insets(3, 20, 3, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(50, 50, 20, 50);
        jPanel2.add(jButtonInscription, gridBagConstraints);

        jButtonRetour.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jButtonRetour.setText("Retour");
        jButtonRetour.setMargin(new java.awt.Insets(3, 20, 3, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(50, 50, 20, 50);
        jPanel2.add(jButtonRetour, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(jPanel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    public javax.swing.JButton getInscriptionButton() {
        return jButtonInscription;
    }

    public javax.swing.JButton getRetourButton() {
        return jButtonRetour;
    }

    public String getPseudoField() {
        String pseudo = jTextFieldPseudo.getText();
        if (pseudo.equals("")) {
            pseudo = null;
        }
        return pseudo;
    }

    /**
     * Renvoie le mot de passe entre dans les deux champs mdp.
     *
     * @return le mot de passe ou null si les deux mots de passe ne sont pas
     * identiques.
     */
    public String getPasswordField() {
        String mdp = "";
        for (char c : jPasswordField.getPassword()) {
            mdp += c;
        }
        String mdpc = "";
        for (char c : jPasswordFieldConfirmation.getPassword()) {
            mdpc += c;
        }

        jPasswordField.setText("");
        jPasswordFieldConfirmation.setText("");

        if (mdp.equals(mdpc) && Membre.estMdpValide(mdp)) {
            return mdp;
        } else {
            return null;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInscription;
    private javax.swing.JButton jButtonRetour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JPasswordField jPasswordFieldConfirmation;
    private javax.swing.JTextField jTextFieldPseudo;
    // End of variables declaration//GEN-END:variables
}
