/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjetJava;

import javax.swing.JOptionPane;

/**
 * Panel contenant le jeu qui est entre en parametre.
 *
 * @author deux
 */
public class JeuPanel extends javax.swing.JPanel {

    /**
     * Creation du Panel et lancement du jeu.
     *
     * @param jeu
     * @param u
     * @param diff
     */
    public JeuPanel(String jeu, Utilisateur u, int diff) {
        initComponents();
        this.titleLabel.setText(jeu);
        switch (jeu) {
            case "Bataille Navale":
                try {
                    BatailleNavale.BatailleNavale bat = new BatailleNavale.BatailleNavale(u, diff);
                    jeuPanel.add(bat);
                    synchronized (bat) {
                        bat.jeu();
                        bat.wait();
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Une ou plusieurs images de la bataille navale sont absentes");
                }
                break;

            case "Pendu":
                break;

            default:
                JOptionPane.showMessageDialog(null, "Votre jeu est inconnu");

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        titleLabel = new javax.swing.JLabel();
        quitButton = new javax.swing.JButton();
        jeuPanel = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(640, 360));
        setPreferredSize(new java.awt.Dimension(854, 480));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWeights = new double[] {0.4, 0.6};
        layout.rowWeights = new double[] {0.15, 0.7, 0.15};
        setLayout(layout);

        titleLabel.setFont(new java.awt.Font("Ubuntu", 0, 30)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Test");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(titleLabel, gridBagConstraints);

        quitButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        quitButton.setText("Abandon");
        quitButton.setMargin(new java.awt.Insets(3, 20, 3, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        add(quitButton, gridBagConstraints);

        jeuPanel.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(jeuPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jeuPanel;
    private javax.swing.JButton quitButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
