/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjetJava;

/**
 *
 * @author edeux
 */
public class StatsFrame extends javax.swing.JFrame {

    /**
     * Creates new form StatsFrame
     */
    public StatsFrame(Identification id) {
        initComponents();
        setVisible(true);
        Membre victoireMembre = id.meilleurPartiesGagnees("Total");
        victoiresLabel.setText(victoireMembre.getPseudo());
        ratioLabel.setText(id.meilleurRatio("Total").getPseudo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statsGeneralPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        victoiresLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ratioLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Statistiques des meilleurs joueurs");
        setMaximumSize(null);
        setPreferredSize(new java.awt.Dimension(640, 360));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        statsGeneralPanel.setLayout(new java.awt.GridLayout(4, 1));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Joueur avec le plus grand nombre de victoires");
        statsGeneralPanel.add(jLabel1);

        victoiresLabel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        victoiresLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        victoiresLabel.setText("jLabel2");
        statsGeneralPanel.add(victoiresLabel);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Joueur avec le meilleur ratio");
        statsGeneralPanel.add(jLabel3);

        ratioLabel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        ratioLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ratioLabel.setText("jLabel4");
        statsGeneralPanel.add(ratioLabel);

        getContentPane().add(statsGeneralPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel ratioLabel;
    private javax.swing.JPanel statsGeneralPanel;
    private javax.swing.JLabel victoiresLabel;
    // End of variables declaration//GEN-END:variables
}
